sudo: false
language: nodejs
node_js:
- 8
- "stable"

git:
    depth:
        1

addons:
    apt:
        update: true

before_install:
# Repo for newer Node.js versions
- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
# Repo for Yarn
- sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn
cache:
    yarn: true
    directories:
    - $HOME/.yarn-cache
    - node_modules

before_script:
- node -v
- yarn

script:
- yarn lint
- yarn test
- yarn build:prod

after_success:
- "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
