sudo: true
language: nodejs
node_js:
- "node"

cache:
    yarn: true
    directories:
    - $HOME/.yarn-cache
    - node_modules

git:
    depth:
        1

addons:
    apt:
        update: true

before_install:
- nvm install 10.9.0
- nvm alias default 10.9.0
- node -v
- npm -v
- npm install -g yarn
- yarn -v

install:
- yarn

script:
- yarn lint
- yarn test
- yarn build

after_success:
- "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
