sudo: false
language: nodejs
node_js:
- 8
- "stable"

git:
    depth:
        1

addons:
    apt:
        update: true
        sources:
            - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
              key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
            packages:
            - yarn

cache:
    yarn: true
    directories:
    - node_modules

before_script:
- node -v
- yarn

script:
- yarn lint
- yarn test
- yarn build:prod

after_success:
- "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
